symmetryinvestments/autowrap

.travis.yml, python2/.gitignore, python2/Makefile, python2/build_and_test_silly.sh, python2/ci.sh, python2/contract/Makefile, python2/contract/dub.sdl, python2/contract/dub.selections.json, python2/contract/source/contract.d, python2/contract/tests/test_contract.py, python2/dub.sdl, python2/dub.selections.json, python2/silly.d, python2/source/python/bindings.dpp, python2/source/python/util.d
Adds tests to document and run assumptions about the Python C API at the border between the two languages.
Python classes will come next.
=> Contract tests with scalar values

pynih/contract/source/contract/main.d, pynih/contract/source/contract/pyclass.d, pynih/contract/source/contract/udt.d, pynih/contract/tests/test_pyclass.py, pynih/contract/tests/test_scalars.py, pynih/source/python/boilerplate.d, pynih/source/python/conv.d, pynih/source/python/package.d, pynih/source/python/raw.dpp, pynih/source/python/type.d
A proprietary codebase was used to validate the new Python implementation and required a few changes.
=> Changes required to use it with a real project

csharp/dub.sdl, csharp/source/autowrap/csharp/csharp.d, csharp/source/autowrap/csharp/dlang.d
=> Fix #45 - use string interpolation from scriptlike.

reflection/source/autowrap/common.d
Lines 9 and 10 are the important parts, the rest is just whitespace.
=> Wrap DllMain in static if.

csharp/source/autowrap/csharp/Boilerplate.cs, csharp/source/autowrap/csharp/boilerplate.d, csharp/tests/Wrapper.cs
#36 Ensure that strings are copied into .NET and released from D.
=> String Ownership

python/source/autowrap/python/boilerplate.d
doesn't compile on windows otherwise.
=> missing dllMainMixinStr import in wrapAll

Makefile, examples/pyd/dub.sdl, examples/pyd/source/app.d, examples/pyd/source/const_.d, examples/pyd/source/testdll.d, examples/simple/source/app.d, examples/simple/source/structs.d, pynih/.gitignore, pynih/source/autowrap/pynih/package.d, pynih/source/autowrap/pynih/wrap.d, pynih/source/python/conv/d_to_python.d, pynih/source/python/conv/python_to_d.d, pynih/source/python/type.d, python/source/autowrap/python/boilerplate.d, reflection/source/autowrap/reflection.d, tests/test_pyd.py, tests/test_simple_pynih_only.py
This is far messier than it should be. The main reason being that I thought that fixing the failures of the pynih backend going through the pyd tests would be easier than it turned out to be.
=> Enable running the pyd tests with the pynih backend

examples/pyd/source/testdll.d, pynih/source/python/conv/d_to_python.d, pynih/source/python/conv/python_to_d.d, pynih/source/python/raw.dpp, pynih/source/python/type.d, reflection/source/autowrap/reflection.d, tests/test_pyd.py
The code up until this PR punted on converting delegates and returned a null pointer in either direction. With this PR it's now possible to pass python functions as callbacks to D code that accepts delegates.
=> Pynih fix null delegate

pynih/source/python/type.d, reflection/source/autowrap/reflection.d, tests/test_pyd.py
This doesn't wrap opBinaryRight yet.
=> pynih binary operators (self on the left)

.travis.yml, Makefile, dub.sdl, examples/issues/dub.sdl, examples/numpy/dub.sdl, examples/pyd/dub.sdl, examples/simple/dub.sdl
=> Travis python3

pynih/source/python/raw.dpp, pynih/source/python/type.d, tests/test_pyd.py
Preliminary (and bad!) support for opSlice. Unfortunately the existing pyd tests aren't particularly good, this shouldn't pass and does.
=> Pynih opslice

examples/pyd/source/def.d, pynih/source/python/conv/python_to_d.d, pynih/source/python/raw.dpp, pynih/source/python/type.d, tests/test_pyd.py, tests/test_simple_pynih_only.py
Now all pyd tests with the pynih backend pass except for the inheritance one.
=> Pynih refactor func calls

Makefile, pynih/contract/tests/test_pyclass.py, pynih/source/python/conv/python_to_d.d, pynih/source/python/type.d, tests/test_pyd.py, tests/test_simple_pynih_only.py, tests/ut/pynih/python/conv.d
Unfortunately still has the same issues as pyd has with it, namely #61 and #62
=> Pynih inheritance

examples/simple/source/wrap_all.d, pynih/source/python/type.d, tests/test_simple.py
=> Fix immutable class members

examples/phobos/Makefile, examples/phobos/source/app.d, examples/phobos/std_file/dub.sdl, examples/phobos/std_file/dub.selections.json, examples/phobos/std_file/source/app.d, examples/phobos/tests/test_std_file.py
It fails to import, but it compiles and links.
=> Phobos std file project

examples/phobos/Makefile, examples/phobos/tests/test_std_math.py
The Makefile is now much simpler.
=> Use a canned sequence (macro) in the Makefile

csharp/tests/dub.selections.json, dub.selections.json, examples/issues/dub.selections.json, examples/numpy/dub.selections.json, examples/phobos/Makefile, examples/phobos/dub.selections.json, examples/phobos/std_datetime/dub.selections.json, examples/phobos/std_file/dub.selections.json, examples/phobos/std_math/dub.selections.json, examples/phobos/std_mmfile/dub.sdl, examples/phobos/std_mmfile/dub.selections.json, examples/phobos/std_mmfile/source/app.d, examples/phobos/tests/test_std_mmfile.py, examples/pyd/dub.selections.json, examples/simple/dub.selections.json, pynih/contract/dub.selections.json
But fails with this linker error with pyd:
```
ImportError: /home/atila/kaleidic/autowrap/examples/phobos/std_mmfile/lib/pyd/std_mmfile.so: undefined symbol: _D54TypeInfo_PS3std5stdio4File__T16BinaryWriterImplVbi1ZQx6__initZ
```
=> std.mmfile can be imported by pynih

translate/backend/csharp.py, translate/python_to_ir.py
Nothing really works yet, but it's a step in the right direction.
=> Small improvements to the translation code

csharp/source/autowrap/csharp/common.d, csharp/source/autowrap/csharp/dlang.d, csharp/source/autowrap/csharp/package.d, examples/issues/dub.sdl
went through fixing some issues with csharp backend.  issues found by running:
```bash
cd examples/issues
dub run --config=csharp
```
=> some fixes to csharp backend

examples/issues/source/issues.d, examples/phobos/std_datetime/source/app.d, examples/phobos/std_experimental/source/app.d, examples/phobos/std_file/source/app.d, examples/phobos/std_net/source/app.d, examples/phobos/std_zip/source/app.d, pynih/source/python/conv/d_to_python.d, pynih/source/python/type.d, tests/test_issues.py
I don't see an interface for this for pyd.
=> pynih supports #268
